export const videoCategories = {
  Action: [
    {
      id: 1,
      title: "Mad Max: Fury Road",
      poster: "https://image.tmdb.org/t/p/w185/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      rating: 4.5,
      year: 2015,
    },
    {
      id: 2,
      title: "John Wick",
      poster: "https://image.tmdb.org/t/p/w185/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
      rating: 4.2,
      year: 2014,
    },
    {
      id: 3,
      title: "Die Hard",
      poster: "https://image.tmdb.org/t/p/w185/gBYhjuq0ZEDN710C5sKVq45y1pA.jpg",
      rating: 3.9,
      year: 1988,
    },
    {
      id: 4,
      title: "Gladiator",
      poster: "https://image.tmdb.org/t/p/w185/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      rating: 4.1,
      year: 2000,
    },
    {
      id: 5,
      title: "The Godfather",
      poster: "https://image.tmdb.org/t/p/w185/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
      rating: 9.2,
      year: 1972,
    },
  ],
  Comedie: [
    {
      id: 5,
      title: "Superbad",
      poster: "https://image.tmdb.org/t/p/w185/jlHTg4rr36WfkDHvsmkYciHjCq0.jpg",
      rating: 4.3,
      year: 2007,
    },
    {
      id: 6,
      title: "The Hangover",
      poster: "https://image.tmdb.org/t/p/w185/wF8XIPZeZEfNJbYNXaZPDnFZd0m.jpg",
      rating: 4.0,
      year: 2009,
    },
    {
      id: 7,
      title: "Step Brothers",
      poster: "https://image.tmdb.org/t/p/w185/rWbsxdwF9qQzpTPCLmDfVnVqTK1.jpg",
      rating: 3.8,
      year: 2008,
    },
    {
      id: 8,
      title: "The 40-Year-Old Virgin",
      poster: "https://image.tmdb.org/t/p/w185/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      rating: 4.2,
      year: 2005,
    },
    {
      id: 9,
      title: "The Dark Knight",
      poster: "https://image.tmdb.org/t/p/w185/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      rating: 9.0,
      year: 2008,
    },
  ],
  Drame: [
    {
      id: 9,
      title: "The Shawshank Redemption",
      poster: "https://image.tmdb.org/t/p/w500/q6y0j8L0x2z0U6Rj3B6Fm4yU2Zt.jpg",
      rating: 4.4,
      year: 1994,
    },
    {
      id: 10,
      title: "Forrest Gump",
      poster: "https://image.tmdb.org/t/p/w500/5GxGv6v1t4Gv6t8J5Zt7dVZcV6Z.jpg",
      rating: 4.1,
      year: 1994,
    },
    {
      id: 11,
      title: "Fight Club",
      poster: "https://image.tmdb.org/t/p/w185/dJzUnKmDCxe9p4eKSdARCX8LCWv.jpg",
      rating: 4.0,
      year: 1999,
    },
    {
      id: 12,
      title: "Parasite",
      poster: "https://image.tmdb.org/t/p/w185/57MFWGHarg9jid7yfDTka4RmcMU.jpg",
      rating: 4.3,
      year: 2019,
    },
    {
      id: 13,
      title: "Pulp Fiction",
      poster: "https://image.tmdb.org/t/p/w185/uefbFPDvWahMlNQeAGkWWPlIudI.jpg",
      rating: 8.9,
      year: 1994,
    },
  ],
  Horreur: [
    {
      id: 13,
      title: "Get Out",
      poster: "https://image.tmdb.org/t/p/w185/890UDXYal6i8A9NbMV5TAxZpOzH.jpg",
      rating: 3.9,
      year: 2017,
    },
    {
      id: 14,
      title: "A Quiet Place",
      poster: "https://image.tmdb.org/t/p/w185/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
      rating: 4.2,
      year: 2018,
    },
    {
      id: 15,
      title: "The Conjuring",
      poster: "",
      rating: 3.7,
      year: 2013,
    },
    {
      id: 16,
      title: "It",
      poster: "https://image.tmdb.org/t/p/w185/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      rating: 4.0,
      year: 2017,
    },
    {
      id: 17,
      title: "The Shawshank Redemption",
      poster: "https://image.tmdb.org/t/p/w185/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      rating: 4.4,
      year: 1994,
    },
  ],
};
